import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from '@/redux/provider';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {

  title: "F2-Fintech Admin Panel",

  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}

export default RootLayout
